/*                    F A C E P L A T E . C P P
 * BRL-CAD
 *
 * Copyright (c) 2018-2026 United States Government as represented by
 * the U.S. Army Research Laboratory.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * version 2.1 as published by the Free Software Foundation.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this file; see the file named COPYING for more
 * information.
 */
/** @file faceplate.cpp
 *
 * Testing routines for drawing "built-in" faceplate view elements
 *
 */

#include "common.h"

#include <stdio.h>
#include <fstream>

#include <bu.h>
#include <icv.h>
#include <imgstream/fbserv.h>
#include "rt/view.h"
#include "view_test_util.h"
#include <ged.h>
#include <ged/draw_obol.h>

#define ADIFF_THRES 0.99

extern "C" int img_cmp(int id, struct ged *gedp, const char *cdir, bool clear_scene, bool clear_image, int soft_fail, fastf_t approximate_check, const char *clear_root, const char *img_root);
extern "C" int img_not_empty(int id, struct ged *gedp, const char *cdir, bool clear_scene, bool clear_image, int soft_fail, const char *clear_root, const char *img_root);
extern "C" int unpack_apng(const char *src_dir, const char *apng_name, const char *out_dir, const char *prefix);

int
main(int ac, char *av[]) {
    struct ged *gedp;
    struct bu_vls fname = BU_VLS_INIT_ZERO;
    int need_help = 0;
    int run_unstable_tests = 0;
    int soft_fail = 0;
    int keep_images = 0;
    int ret = BRLCAD_OK;

    bu_setprogname(av[0]);

    struct bu_opt_desc d[5];
    BU_OPT(d[0], "h", "help",            "", NULL,          &need_help, "Print help and exit");
    BU_OPT(d[1], "U", "enable-unstable", "", NULL, &run_unstable_tests, "Test drawing routines known to differ between build configs/platforms.");
    BU_OPT(d[2], "c", "continue",        "", NULL,          &soft_fail, "Continue testing if a failure is encountered.");
    BU_OPT(d[3], "k", "keep",            "", NULL,        &keep_images, "Keep images generated by the run.");
    BU_OPT_NULL(d[4]);

    /* Done with program name */
    int uac = bu_opt_parse(NULL, ac, (const char **)av, d);
    if (uac == -1 || need_help)

    if (ac != 2)
	bu_exit(EXIT_FAILURE, "%s [-h] [-U] <directory>", av[0]);

    if (!bu_file_directory(av[1])) {
	printf("ERROR: [%s] is not a directory.  Expecting control image directory\n", av[1]);
	return 2;
    }

    bool clear_images = !keep_images;

    /* Enable all the experimental logic */
    bu_setenv("LIBRT_USE_COMB_INSTANCE_SPECIFIERS", "1", 1);

    /* Use a local working-directory cache so we do not pollute the user's
     * real BRL-CAD cache and so the test is fully self-contained. */
    char lcache[MAXPATHLEN] = {0};
    bu_dir(lcache, MAXPATHLEN, BU_DIR_CURR, "ged_fp_test_cache", NULL);
    bu_mkdir(lcache);
    bu_setenv("BU_DIR_CACHE", lcache, 1);

    if (!bu_file_exists(av[1], NULL)) {
	printf("ERROR: [%s] does not exist, expecting .g file\n", av[1]);
	return 2;
    }

    unpack_apng(av[1], "faceplate.apng", lcache, "fp");

    /* Open the temp file, then dbconcat argv[1] into it */
    bu_vls_sprintf(&fname, "%s/moss.g", av[1]);
    gedp = ged_open("db", bu_vls_cstr(&fname), 1);

    /* Image baselines use the GED-owned headless Obol render endpoint. */
    const char *s_av[15] = {NULL};
    void *v = ged_view_active_ctx(gedp);
    if (draw_test_obol_view_init(gedp, v, 512, 512) != BRLCAD_OK)
	bu_exit(EXIT_FAILURE, "failed to initialize headless Obol render endpoint\n");

    /***** Sanity - basic wireframe draw *****/
    bu_log("Testing basic db wireframe draw...\n");
    s_av[0] = "draw";
    s_av[1] = "all.g";
    s_av[2] = NULL;
    ged_exec_draw(gedp, 2, s_av);

    s_av[0] = "autoview";
    s_av[1] = NULL;
    ged_exec_autoview(gedp, 1, s_av);

    s_av[0] = "ae";
    s_av[1] = "35";
    s_av[2] = "25";
    s_av[3] = NULL;
    ged_exec_ae(gedp, 3, s_av);
    ret += img_cmp(1, gedp, lcache, true, clear_images, soft_fail, 0, "faceplate_clear", "fp");

    // Check that everything is in fact cleared
    ret += img_cmp(0, gedp, lcache, false, clear_images, soft_fail, 0, "faceplate_clear", "fp");
    bu_log("Done.\n");

    /***** Center Dot *****/
    bu_log("Testing center dot...\n");
    s_av[0] = "view";
    s_av[1] = "faceplate";
    s_av[2] = "center_dot";
    s_av[3] = "1";
    s_av[4] = NULL;
    ged_exec_view(gedp, 4, s_av);
    ret += img_cmp(2, gedp, lcache, false, clear_images, soft_fail, ADIFF_THRES, "faceplate_clear", "fp");

    // Check that turning off works
    s_av[3] = "0";
    ged_exec_view(gedp, 4, s_av);
    ret += img_cmp(0, gedp, lcache, false, clear_images, soft_fail, 0, "faceplate_clear", "fp");
    bu_log("Done.\n");

    /***** Grid *****/
    bu_log("Testing grid...\n");

    s_av[0] = "view";
    s_av[1] = "faceplate";
    s_av[2] = "grid";
    s_av[3] = "1";
    s_av[4] = NULL;
    ged_exec_view(gedp, 4, s_av);
    ret += img_not_empty(3, gedp, lcache, false, clear_images, soft_fail, "faceplate_clear", "fp");

    // Check that turning off works
    s_av[3] = "0";
    ged_exec_view(gedp, 4, s_av);
    ret += img_cmp(0, gedp, lcache, false, clear_images, soft_fail, 0, "faceplate_clear", "fp");
    bu_log("Done.\n");

    /***** Params *****/
    bu_log("Testing parameters reporting...\n");

    // First make the font smaller so we can see all params
    s_av[0] = "view";
    s_av[1] = "faceplate";
    s_av[2] = "params";
    s_av[3] = "font_size";
    s_av[4] = "10";
    s_av[5] = NULL;
    ged_exec_view(gedp, 5, s_av);

    s_av[0] = "view";
    s_av[1] = "faceplate";
    s_av[2] = "params";
    s_av[3] = "1";
    s_av[4] = NULL;
    ged_exec_view(gedp, 4, s_av);
    ret += img_not_empty(4, gedp, lcache, false, clear_images, soft_fail, "faceplate_clear", "fp");

    bu_log("Testing turning on frames per second reporting...\n");

    // So we don't get random values here, override the timing variable values
    bv_frametime_set(DRAW_TEST_BV(v), 1000000000);

    s_av[0] = "view";
    s_av[1] = "faceplate";
    s_av[2] = "params";
    s_av[3] = "fps";
    s_av[4] = "1";
    s_av[5] = NULL;
    ged_exec_view(gedp, 5, s_av);
    ret += img_not_empty(5, gedp, lcache, false, clear_images, soft_fail, "faceplate_clear", "fp");

    // Check that turning off works
    s_av[3] = "0";
    ged_exec_view(gedp, 4, s_av);
    ret += img_cmp(0, gedp, lcache, false, clear_images, soft_fail, 0, "faceplate_clear", "fp");
    bu_log("Done.\n");

    // Restore default font size
    s_av[0] = "view";
    s_av[1] = "faceplate";
    s_av[2] = "params";
    s_av[3] = "font_size";
    s_av[4] = "20";
    s_av[5] = NULL;
    ged_exec_view(gedp, 5, s_av);



    /***** Scale *****/
    bu_log("Testing scale reporting...\n");
    s_av[0] = "view";
    s_av[1] = "faceplate";
    s_av[2] = "scale";
    s_av[3] = "1";
    s_av[4] = NULL;
    ged_exec_view(gedp, 4, s_av);
    ret += img_not_empty(6, gedp, lcache, false, clear_images, soft_fail, "faceplate_clear", "fp");

    // Check that turning off works
    s_av[3] = "0";
    ged_exec_view(gedp, 4, s_av);
    ret += img_cmp(0, gedp, lcache, false, clear_images, soft_fail, 0, "faceplate_clear", "fp");
    bu_log("Done.\n");


    /***** View axes *****/
    bu_log("Testing view axes drawing...\n");
    s_av[0] = "view";
    s_av[1] = "faceplate";
    s_av[2] = "view_axes";
    s_av[3] = "1";
    s_av[4] = NULL;
    ged_exec_view(gedp, 4, s_av);
    ret += img_not_empty(7, gedp, lcache, false, clear_images, soft_fail, "faceplate_clear", "fp");

    // Check that turning off works
    s_av[3] = "0";
    ged_exec_view(gedp, 4, s_av);
    ret += img_cmp(0, gedp, lcache, false, clear_images, soft_fail, 0, "faceplate_clear", "fp");
    bu_log("Done.\n");

    /***** Model axes *****/
    bu_log("Testing model axes drawing...\n");
    s_av[0] = "view";
    s_av[1] = "faceplate";
    s_av[2] = "model_axes";
    s_av[3] = "1";
    s_av[4] = NULL;
    ged_exec_view(gedp, 4, s_av);
    ret += img_not_empty(8, gedp, lcache, false, clear_images, soft_fail, "faceplate_clear", "fp");

    // Check that turning off works
    s_av[3] = "0";
    ged_exec_view(gedp, 4, s_av);
    ret += img_cmp(0, gedp, lcache, false, clear_images, soft_fail, 0, "faceplate_clear", "fp");
    bu_log("Done.\n");

    /***** Framebuffer *****/
    bu_log("Testing framebuffer...\n");
    struct bu_vls fb_img = BU_VLS_INIT_ZERO;
    bu_vls_sprintf(&fb_img, "%s/moss.png", av[1]);
    if (ged_draw_obol_framebuffer_backend_ensure_for_view(gedp, v) !=
	BRLCAD_OK)
	bu_exit(EXIT_FAILURE, "failed to initialize Obol framebuffer backend\n");
    icv_image_t *fb_source = icv_read(bu_vls_cstr(&fb_img),
	BU_MIME_IMAGE_PNG, 0, 0);
    if (!fb_source)
	bu_exit(EXIT_FAILURE, "failed to read framebuffer baseline image\n");
    /* Match png-fb's default conversion of untagged input into a linear
     * framebuffer. */
    fb_source->gamma_corr = 0.5f;
    unsigned char *fb_pixels = icv_data2uchar(fb_source);
    if (!fb_pixels || !gedp->ged_fbs ||
	fbserv_backend_writerect(gedp->ged_fbs, 0, 0,
	    (int)fb_source->width, (int)fb_source->height, fb_pixels) !=
	    (int)(fb_source->width * fb_source->height) ||
	fbserv_backend_flush(gedp->ged_fbs) != 0)
	bu_exit(EXIT_FAILURE, "failed to publish framebuffer baseline image\n");
    bu_free(fb_pixels, "faceplate framebuffer pixels");
    icv_destroy(fb_source);
    bu_vls_free(&fb_img);

    s_av[0] = "view";
    s_av[1] = "faceplate";
    s_av[2] = "fb";
    s_av[3] = "1";
    s_av[4] = NULL;
    ged_exec_view(gedp, 4, s_av);
    ret += img_cmp(9, gedp, lcache, false, clear_images, soft_fail,
	ADIFF_THRES, "faceplate_clear", "fp");

    // Check that turning off works
    s_av[3] = "0";
    ged_exec_view(gedp, 4, s_av);
    ret += img_cmp(0, gedp, lcache, false, clear_images, soft_fail, 0, "faceplate_clear", "fp");

    // Re-enable and make sure clear works
    s_av[3] = "1";
    ged_exec_view(gedp, 4, s_av);
    ret += img_cmp(9, gedp, lcache, false, clear_images, soft_fail,
	ADIFF_THRES, "faceplate_clear", "fp");

    const unsigned char black[3] = {0, 0, 0};
    if (fbserv_backend_clear(gedp->ged_fbs, black) != 0 ||
	fbserv_backend_flush(gedp->ged_fbs) != 0)
	bu_exit(EXIT_FAILURE, "failed to clear Obol framebuffer backend\n");
    ret += img_cmp(0, gedp, lcache, false, clear_images, soft_fail, 0, "faceplate_clear", "fp");

    s_av[0] = "view";
    s_av[1] = "faceplate";
    s_av[2] = "fb";
    s_av[3] = "0";
    s_av[4] = NULL;
    ged_exec_view(gedp, 4, s_av);

    bu_log("Done.\n");


    ged_draw_obol_framebuffer_release(gedp);
    ged_close(gedp);

    if (!keep_images)
	bu_dirclear(lcache);

    return ret;
}


// Local Variables:
// tab-width: 8
// mode: C++
// c-basic-offset: 4
// indent-tabs-mode: t
// c-file-style: "stroustrup"
// End:
// ex: shiftwidth=4 tabstop=8
