= GUI(nged)
:doctype: manpage
:mansource: BRL-CAD
:manmanual: BRL-CAD User Commands

== NAME
gui - Creates an instance of MGED's default Tcl/Tk graphical user interface (GUI).

== SYNOPSIS

[source]
----
gui [{-config} | [b] | [c] | [g]] [{-d} | {display_string}] [{-gd} | {graphics_display_string}] [{-host} | {host_type}] [{id} | {name}] [{-c} | {-h} | {-j} | {-s}]
----


[[description]]
== DESCRIPTION

Creates an instance of MGED's default Tcl/Tk graphical user interface (GUI). The following options are allowed:


_-config b c g_::
Configures the GUI to display the command window, the graphics window, or both. This option is useful only when the GUI is combining the text and graphics windows. See the _-c_ option.


__-d display_string__::
Displays/draws the GUI on the screen indicated by the display_string. Note that this string format is the same as the X DISPLAY environment variable.


__-gd display_string__::
Displays/draws the graphics window on the screen indicated by the display_string. Note that this string format is the same as the X DISPLAY environment variable.


__-host host_type__::
Selects the Obol host used for the GUI graphics panes. `tkobol` is the supported host.


_-id name_::
Specifies the id to use when referring to this instance of the GUI.


_-c_::
Combines text window and display manager windows.


_-s_::
Uses separate text window and display manager windows. This is the default behavior.


_-j_::
Join the collaborative session.


_-h_::
Prints the help message.




[[examples]]
== EXAMPLES

.Open a separate graphics and command GUI.
[example]
====
mged> **gui -id inspect -s**

Creates a separate command window and graphics window identified as _inspect_.

====

.Open only the graphics portion of the GUI.
[example]
====
mged> **gui -config g -id view_only**

Creates a GUI instance named _view_only_ with the graphics window enabled.

====


[[author]]
== AUTHOR

BRL-CAD Team


[[bug_reports]]
== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to devs@brlcad.org
